Repository ARF-SS13/coyotesector-14, pull requests merged in 2025-06, with the labels that each got.

#4 Unvidenoir'd
  Content.Shared/_NF/CCVar/NFCCVars.cs
  Resources/Maps/_NF/Shuttles/Expedition/phantom.yml
  Resources/Maps/_NF/Shuttles/Expedition/wisp.yml
  Resources/Prototypes/Catalog/Cargo/cargo_engines.yml
  Resources/Prototypes/Entities/Objects/Power/antimatter_jar.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Research/arsenal.yml
  Resources/Prototypes/Research/civilianservices.yml
  Resources/Prototypes/Research/industrial.yml
  Resources/Prototypes/_NF/Guidebook/shipyard.yml
  Resources/Prototypes/_NF/Guidebook/shuttle_maps.yml
  Resources/Prototypes/_NF/Shipyard/Expedition/phantom.yml
  Resources/Prototypes/_NF/Shipyard/Expedition/wisp.yml
  Resources/ServerInfo/_NF/Guidebook/Shipyard/Phantom.xml
  Resources/Textures/_NF/Guidebook/shuttle_maps/128x96.rsi/meta.json
  Resources/Textures/_NF/Guidebook/shuttle_maps/128x96.rsi/phantom.png
Labels: S: Untriaged, size/XL

#6 Roleplaying guide placeholder
  Resources/Locale/en-US/guidebook/guides.ftl
  Resources/Prototypes/Guidebook/newplayer.yml
  Resources/ServerInfo/Guidebook/NewPlayer/Controls/Roleplay.xml
Labels: documentation, prototyping pr

#8 Flooftier Outpost -> Redwater Outpost | Ingame rules change.
  Resources/Maps/_NF/Outpost/frontier.yml
  Resources/Prototypes/_NF/Maps/Outpost/frontier.yml
  Resources/ServerInfo/_NF/Guidebook/Rules/Zero_Tolerance.xml
Labels: S: Untriaged, size/XS

#10 Increases the examine Detail range
  Content.Shared/Examine/ExamineSystemShared.cs
Labels: enhancement, S: Untriaged, size/XS

#12 Asteroids & Shortstacks
  Content.Server/Worldgen/Prototypes/BiomePrototype.cs
  Content.Server/Worldgen/Systems/Biomes/BiomeSelectionSystem.cs
  Content.Server/Worldgen/Systems/Carvers/NoiseRangeCarverSystem.cs
  Content.Server/_NF/Worldgen/Components/Carvers/PointSetDistanceCarverComponent.cs
  Content.Server/_NF/Worldgen/Components/Carvers/WorldGenDistanceCarverComponent.cs
  Content.Server/_NF/Worldgen/Systems/Carvers/DistanceProbabilityFilterSystem.cs
  Content.Shared/Materials/SharedMaterialStorageSystem.cs
  Resources/Locale/en-US/_NF/guidebook/guides.ftl
  Resources/Maps/_NF/Outpost/frontier.yml
  Resources/Prototypes/World/noise_channels.yml
  Resources/Prototypes/_NF/Entities/World/Debris/asteroids.yml
  Resources/Prototypes/_NF/Entities/World/Debris/wrecks.yml
  Resources/Prototypes/_NF/Guidebook/expeditions.yml
  Resources/Prototypes/_NF/Guidebook/nf14.yml
  Resources/Prototypes/_NF/Guidebook/sector_topology.yml
  Resources/Prototypes/_NF/Guidebook/shipyard.yml
  Resources/Prototypes/_NF/PointsOfInterest/depots.yml
  Resources/Prototypes/_NF/PointsOfInterest/trade.yml
  Resources/Prototypes/_NF/PointsOfInterest/trademall.yml
  Resources/Prototypes/_NF/World/Biomes/basic.yml
  Resources/Prototypes/_NF/World/worldgen_default.yml
  Resources/ServerInfo/_NF/Guidebook/SectorTopology.xml
  Resources/Textures/_NF/Guidebook/large_icons/128x96.rsi/meta.json
  Resources/Textures/_NF/Guidebook/large_icons/128x96.rsi/sector_map.png
  Resources/Textures/_NF/Guidebook/shuttle_maps/128x96.rsi/meta.json
Labels: size/L, S: Untriaged

#11 Oops *rotates your dock cutely (lynx fix)
  Resources/Maps/_NF/Shuttles/Coyote/Mercenary/lynx.yml
Labels: S: Untriaged, size/XS

#14 Replaces Recycler on Courthouse, add reclaimer drain to Bahamas. (#2946)
  Content.Shared/Materials/SharedMaterialStorageSystem.cs
  Resources/Prototypes/Entities/Clothing/Back/backpacks.yml
  Resources/Prototypes/Entities/Clothing/Back/duffel.yml
  Resources/Prototypes/Entities/Clothing/Back/satchel.yml
  Resources/Prototypes/Entities/Clothing/Head/helmets.yml
  Resources/Prototypes/Entities/Objects/Misc/handcuffs.yml
  Resources/Prototypes/Entities/Objects/Shields/shields.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/knife.yml
Labels: S: Untriaged, size/S
